### ISSUE TITLE
关于默认播放内核

### ISSUE THREAD

**Issue by LilligantMatsuri** [RyensX/SakuraAnime2Plugin#2]
#### 环境
> Android: 10
> MediaBox: 2.4(43) Release
> SakuraAnime2Plugin: 1.1(3)
> API: 2

#### 描述
　　起初我将默认播放内核设置为 IjkPlayer，发现部分番剧在 APP 内无法播放，提示“_播放错误，网络错误或目标资源已失效_”，但使用外部浏览器打开时却能够播放，并且使用不同网络多次尝试均得到同样结果，于是怀疑没有正确解析。我抓取了网络请求，并参照了 [VideoPlayPageDataComponent.kt](https://github.com/RyensX/SakuraAnime2Plugin/blob/master/app/src/main/java/com/su/sakuraanime2plugin/plugin/components/VideoPlayPageDataComponent.kt) 的源码，认为解析应该没有问题。之后将播放内核从 IjkPlayer 切换回 Exo2Player，能够正常播放。

　　以 [CLANNAD](https://m.yhdmp.net/showp/7101.html) 的播放列表2为例，通过监视网络请求能够获取如下播放地址：
```
https://m.yhdmp.net/yxsf/player/dpx2/alm3p.html?url=%2fgm3px%2fbd%2d20070019%5fSumiSora%5fBDRIP%5f720P%5fBIG5%5frbak%2f%5bSumiSora%5d%5b4641f42a5e3290d6%5d%5b01%5d%5bBD%2d720P%5d%5bBIG5%5d%20nvl%2drm&getplay_url=%2F_getplay%3Faid%3D7101%26playindex%3D1%26epindex%3D0%26r%3D0.08952431630083257&vlt_l=0&vlt_r=0
```
同时可以观察到 blob 中包含的 m3u：

![QQ截图20220808131025](https://user-images.githubusercontent.com/26195226/183343746-64bf4ddc-fc1b-4053-8ace-47bfde1935ea.png)

随意下载其中一个分片，以视频方式打开可直接播放，将后缀名改为“.ts”后可查看具体编码信息。

　　在尝试多部番剧后，我发现 IjkPlayer 无法播放的视频流大都存在一个共性，也就是以 gif 格式分段存储在百家号中（即上图所示的 `https://pic.rmb.bdstatic.com/bjh/*`）。我尚未进一步研究，目前只得到这些信息。

#### 推测
　　可能与 GSYVideoPlayer 的配置有关，不同内核解码方式差异导致此现象，问题未必来自 MediaBox 本身。

**Comment by RyensX** [comment]
是的，这个内核是有点问题，但是对部分编码视频有效，有时候exo不能播放就可以尝试一下更换这个(PlayAction是支持自定义内核的，具体看代码文档注释)。我后面再详细排查一下

**Comment by LilligantMatsuri** [comment]
好的，谢谢回复！感谢大佬对这款软件的付出。

**Comment by RyensX** [comment]
如果有兴趣，欢迎贡献插件到[插件仓库](https://github.com/RyensX/MediaBoxPluginRepository)
