### ISSUE TITLE
503

### ISSUE THREAD

**Issue by smarttommyau** [RyensX/SakuraAnime2Plugin#4]
![Screenshot_20230131_195445_com su mediabox](https://user-images.githubusercontent.com/75346987/215753125-1bd45f90-976c-4ead-916e-876974d10ee8.jpg)
这个是不是cloudflare的锅？我用浏览器就能进。

**Comment by RyensX** [comment]
> ![Screenshot_20230131_195445_com su mediabox](https://user-images.githubusercontent.com/75346987/215753125-1bd45f90-976c-4ead-916e-876974d10ee8.jpg)
> 这个是不是cloudflare的锅？我用浏览器就能进。

之前有一段时间加个这个。然后我做了适配它又好了，就先放着了

**Comment by RyensX** [comment]
修改了，更新一下试试
